USE FLORISTERIA;

SELECT * FROM CATEGORIAS;

INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('ARREGLOS FLORALES', 'CATEGORIA PARA ARREGLOS FLORALES', 'imagen.png', '2023-03-21', 1, NULL);

INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('ARREGLOS FLORALES PARA REGALAR', 'CATEGORIA PARA ARREGLOS FLORALES PARA REGALAR', 'imagen.png', '2023-03-21', 1, 1);
INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('ARREGLOS FLORALES CON CHOCOLATES', 'CATEGORIA PARA ARREGLOS FLORALES PARA REGALAR CON CHOCOLATES', 'imagen.png', '2023-03-21', 1, 1);
INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('ARREGLOS FLORALES FUNEBRES', 'CATEGORIA PARA ARREGLOS FUNEBRES', 'imagen.png', '2023-03-21', 1, 1);


INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('ROSAS', 'CATEGORIA PARA ARREGLOS EN ROSAS', 'imagen.png', '2023-03-21', 1, 2);
INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('GIRASOLES', 'CATEGORIA PARA ARREGLOS EN GIRASOLES', 'imagen.png', '2023-03-21', 1, 2);
INSERT INTO CATEGORIAS(NOMBRE, DESCRIPCION, FOTO, FECHA_CREACION, ESTADO, ID_PADRE_CATEGORIA) VALUES ('EXÓTICOS', 'CATEGORIA PARA ARREGLOS EXÓTIVOS', 'imagen.png', '2023-03-21', 1, 2);



COMMIT;